### ISSUE TITLE
Problem when running serval

### ISSUE THREAD

**Issue by msotov** [mzechmeister/serval#11]
Hi,

I've been trying to test serval using the example from the README:

serval gj699 data/HARPS/gj699/ -inst HARPS -targ gj699 -vref auto

I first got the following error: serval: error: unrecognized arguments: -vref auto

I then removed that option, but got this:
Traceback (most recent call last):
  File "/Users/maritza/bin/serval", line 2309, in <module>
    sys.exit(serval())
  File "/Users/maritza/bin/serval", line 941, in serval
    sp = Spectrum(filename, inst=inst, pfits=2 if 'HARP' in inst else True, drs=drs, fib=fib, targ=targ, verb=True)
  File "/Users/maritza/serval/src/read_spec.py", line 151, in __init__
    self.bjd, self.berv = brv_we14py.bjdbrv(jd_utc=jd_utc[0], ra=ra, dec=de, obsname=obsname, pmra=targ.pmra, pmdec=targ.pmde, parallax=0., rv=0., zmeas=[0])
  File "/Users/maritza/serval/src/brv_we14py.py", line 64, in bjdbrv
    pmdec=pmdec, px=parallax, lat=lat, longi=lon, alt=elevation, **kwargs)

Can you please help me with this?
Thanks!
Maritza.

**Comment by mzechmeister** [comment]
Thanks for the report!

I have updated the documentation (aa96afb9a2631153fd29abacc24522fe9f9ade42). Just remove the `-vref` option. I have also created a [wiki page](../wiki) with some more explanations.
