### ISSUE TITLE
Installation issues on Mac OSX

### ISSUE THREAD

**Issue by gummiks** [mzechmeister/serval#2]
Hi Mathias,

I am trying to install SERVAL on my Macbook Pro, but I am having some issues.

I went through the installation instructions (including compiling the c program instructions, which ran fine). 

However, when I try to run serval.py --help, then I get the following error message:

```
Gumundurs-MacBook-Pro:BarCor gks$ $SERVAL/src/serval.py --help
/Users/gks/Dropbox/mypylib/notebooks/GIT/serval/src/calcspec.py:87: SyntaxWarning: import * only allowed at module level
  def qfacmask(lnw,f,sz=26,thres=3000.,plot=False):
Traceback (most recent call last):
  File "/Users/gks/Dropbox/mypylib/notebooks/GIT/serval//src/serval.py", line 33, in <module>
    from calcspec import *
  File "/Users/gks/Dropbox/mypylib/notebooks/GIT/serval/src/calcspec.py", line 5, in <module>
    import cubicSpline
  File "/Users/gks/Dropbox/mypylib/notebooks/GIT/serval/src/cubicSpline.py", line 27, in <module>
    import spl_int
ImportError: dlopen(/Users/gks/Dropbox/mypylib/notebooks/GIT/serval/src/spl_int.so, 2): no suitable image found.  Did find:
	/Users/gks/Dropbox/mypylib/notebooks/GIT/serval/src/spl_int.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/gks/Dropbox/mypylib/notebooks/GIT/serval/src/spl_int.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

Then I tried compiling spl_int.f by running:

`gfortran -dynamiclib spl_int.f -o spl_int.so
`

but then I got the following error:

`Gumundurs-MacBook-Pro:src gks$ ./serval.py
Traceback (most recent call last):
  File "./serval.py", line 33, in <module>
    from calcspec import *
  File "/Users/gks/Dropbox/mypylib/notebooks/GIT/serval/src/calcspec.py", line 5, in <module>
    import cubicSpline
  File "/Users/gks/Dropbox/mypylib/notebooks/GIT/serval/src/cubicSpline.py", line 27, in <module>
    import spl_int
ImportError: dynamic module does not define init function (initspl_int)`

Do you have any recommendations on what to try next ?

**Comment by mzechmeister** [comment]
Hi Gudmundur, 

Thanks for your interest and sorry for my late reply. I only now noticed your message.

Please try:
`f2py -c -m spl_int spl_int.f`

This is also given in line 2 of [spl_int.f](https://github.com/mzechmeister/serval/blob/master/src/spl_int.f).
I will include this into the ReadMe.

This solved the `ImportError: dlopen(./spl_int.so, 2): no suitable image found.` for another Mac user.

**Comment by gummiks** [comment]
That indeed fixed it ! Thanks !
