### ISSUE TITLE
On the uncertainties of RVs of spectra without drift correction (HARPS)

### ISSUE THREAD

**Issue by asmasca** [mzechmeister/serval#41]
I've seen that when using observations with drift correction, the error bar of the RVs include the error on the drift. Is there any extra noise added to the RVs of spectra taken without drift correction?

**Comment by mzechmeister** [comment]
Good point. No, there is no extra uncertainty added.

It happens in
https://github.com/mzechmeister/serval/blob/d94655e9ee559c85cd40859d8f6638e23b2bb0e3/src/serval.py#L2031-L2032

[np.nan_to_num](https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html) defaults to `nan=0.0`. Other values for drift and its uncertainty could be put in here. They will dependent instrument and require experience with the instrument performance.
It could be a command line option. But then it will be more difficult to figure out later, which points were affected. I think, it is better to add it at a later stage, i.e. during RV analysis.

Btw, the [srv.py](https://github.com/mzechmeister/serval/blob/master/src/srv.py) script marks them as open circles.

**Comment by asmasca** [comment]
Thanks for the answer! I agree it's better to add it during the analysis. Just wanted to be sure what the code was doing, as I'm currently working with a series that has some measurements with and some without drift correction on the same instrument.

**Comment by mzechmeister** [comment]
Good luck!
